# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/FPGA/PYNQ-Z1_C.xdc

# Block Designs: bd/pr_bd/pr_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pr_bd || ORIG_REF_NAME==pr_bd} -quiet] -quiet

# IP: bd/pr_bd/ip/pr_bd_processing_system7_0_0/pr_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pr_bd_processing_system7_0_0 || ORIG_REF_NAME==pr_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/pr_bd/ip/pr_bd_axi_dma_0_0/pr_bd_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pr_bd_axi_dma_0_0 || ORIG_REF_NAME==pr_bd_axi_dma_0_0} -quiet] -quiet

# IP: bd/pr_bd/ip/pr_bd_ps7_0_axi_periph_0/pr_bd_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pr_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==pr_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/pr_bd/ip/pr_bd_rst_ps7_0_100M_0/pr_bd_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pr_bd_rst_ps7_0_100M_0 || ORIG_REF_NAME==pr_bd_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/pr_bd/ip/pr_bd_axi_mem_intercon_0/pr_bd_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pr_bd_axi_mem_intercon_0 || ORIG_REF_NAME==pr_bd_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/pr_bd/ip/pr_bd_axis_data_fifo_0_0/pr_bd_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pr_bd_axis_data_fifo_0_0 || ORIG_REF_NAME==pr_bd_axis_data_fifo_0_0} -quiet] -quiet

# IP: /home/charlie/PR/PR.srcs/sources_1/bd/pr_bd/ip/pr_bd_MCP3008_Interface_0_0/pr_bd_MCP3008_Interface_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pr_bd_MCP3008_Interface_0_0 || ORIG_REF_NAME==pr_bd_MCP3008_Interface_0_0} -quiet] -quiet

# IP: /home/charlie/PR/PR.srcs/sources_1/bd/pr_bd/ip/pr_bd_mcp_filler_0_0/pr_bd_mcp_filler_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pr_bd_mcp_filler_0_0 || ORIG_REF_NAME==pr_bd_mcp_filler_0_0} -quiet] -quiet

# IP: /home/charlie/PR/PR.srcs/sources_1/bd/pr_bd/ip/pr_bd_xlconcat_0_0/pr_bd_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pr_bd_xlconcat_0_0 || ORIG_REF_NAME==pr_bd_xlconcat_0_0} -quiet] -quiet

# IP: bd/pr_bd/ip/pr_bd_auto_pc_0/pr_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pr_bd_auto_pc_0 || ORIG_REF_NAME==pr_bd_auto_pc_0} -quiet] -quiet

# IP: bd/pr_bd/ip/pr_bd_auto_pc_1/pr_bd_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pr_bd_auto_pc_1 || ORIG_REF_NAME==pr_bd_auto_pc_1} -quiet] -quiet

# IP: bd/pr_bd/ip/pr_bd_auto_us_0/pr_bd_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pr_bd_auto_us_0 || ORIG_REF_NAME==pr_bd_auto_us_0} -quiet] -quiet

# XDC: /home/charlie/FPGA/mcp1/mcp1.gen/sources_1/bd/pr_bd/pr_bd_ooc.xdc
