library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;

entity top is

    port(
    clk : in std_logic;
    rst : in std_logic;
    start : in std_logic;
    data_in : in std_logic_vector(7 downto 0);
    data_out : out std_logic_vector(7 downto 0));

end top;

architecture Behavioral of top is

    -- SPI signals generated by the transmitter
    signal clk_out   : std_logic;
    signal MOSI_tx   : std_logic;
    signal CS_tx     : std_logic;

begin

  tx: entity work.SPI_Transmitter
    generic map (
      DATA_WIDTH => 8
    )
    port map (
      data_in => data_in,
      clk     => clk,
      rst     => rst,   -- active low reset for transmitter
      start   => start,
      clk_out => clk_out,
      MOSI    => MOSI_tx,
      CS      => CS_tx
    );

  rx: entity work.SPI_recv
    port map (
      SCLK     => clk_out,
      MOSI     => MOSI_tx,
      CS       => CS_tx,
      clk      => clk,
      rst      => rst,
      data_out => data_out
    );

end Behavioral;

