# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/charlie/FPGA/mcp1/mcp1.srcs/sources_1/bd/pr_bd/ip/pr_bd_axi_dma_0_0/pr_bd_axi_dma_0_0.xci
# IP: The module: 'pr_bd_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/charlie/FPGA/mcp1/mcp1.gen/sources_1/bd/pr_bd/ip/pr_bd_axi_dma_0_0/pr_bd_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pr_bd_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/charlie/FPGA/mcp1/mcp1.gen/sources_1/bd/pr_bd/ip/pr_bd_axi_dma_0_0/pr_bd_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'pr_bd_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/charlie/FPGA/mcp1/mcp1.gen/sources_1/bd/pr_bd/ip/pr_bd_axi_dma_0_0/pr_bd_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pr_bd_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/charlie/FPGA/mcp1/mcp1.srcs/sources_1/bd/pr_bd/ip/pr_bd_axi_dma_0_0/pr_bd_axi_dma_0_0.xci
# IP: The module: 'pr_bd_axi_dma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/charlie/FPGA/mcp1/mcp1.gen/sources_1/bd/pr_bd/ip/pr_bd_axi_dma_0_0/pr_bd_axi_dma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'pr_bd_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/charlie/FPGA/mcp1/mcp1.gen/sources_1/bd/pr_bd/ip/pr_bd_axi_dma_0_0/pr_bd_axi_dma_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'pr_bd_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/charlie/FPGA/mcp1/mcp1.gen/sources_1/bd/pr_bd/ip/pr_bd_axi_dma_0_0/pr_bd_axi_dma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pr_bd_axi_dma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
